export interface Category {
  id: string;
  name: string;
  slug: string;
  iconName: string;
  productCount: number;
  gradient: string;
  iconColor: string;
}

export interface ProductVariant {
  id: string;
  name: string;
  color?: string;
  size?: string;
  price: number;
  inStock: boolean;
}

export interface Product {
  id: string;
  name: string;
  slug: string;
  price: number;
  compareAtPrice: number | null;
  images: string[];
  rating: number;
  reviewCount: number;
  category: string;
  categoryLabel: string;
  badge: 'NEW' | 'TRENDING' | 'SALE' | 'BESTSELLER' | null;
  variants: ProductVariant[];
  description: string;
  shippingDays: string;
  warehouse: 'US' | 'CN';
  inStock: boolean;
  stockCount: number;
}

export interface Review {
  id: string;
  productId: string;
  authorName: string;
  rating: number;
  date: string;
  title: string;
  body: string;
  verified: boolean;
}

export const categories: Category[] = [
  {
    id: 'cat-1',
    name: "Women's Fashion",
    slug: 'womens-fashion',
    iconName: 'Shirt',
    productCount: 2840,
    gradient: 'from-rose-100 to-pink-50',
    iconColor: 'text-rose-500',
  },
  {
    id: 'cat-2',
    name: 'Pet Supplies',
    slug: 'pet-supplies',
    iconName: 'PawPrint',
    productCount: 1520,
    gradient: 'from-sky-100 to-blue-50',
    iconColor: 'text-sky-500',
  },
  {
    id: 'cat-3',
    name: 'Home & Garden',
    slug: 'home-garden',
    iconName: 'Home',
    productCount: 3100,
    gradient: 'from-emerald-100 to-green-50',
    iconColor: 'text-emerald-500',
  },
  {
    id: 'cat-4',
    name: 'Health & Beauty',
    slug: 'health-beauty',
    iconName: 'Sparkles',
    productCount: 2200,
    gradient: 'from-amber-100 to-yellow-50',
    iconColor: 'text-amber-500',
  },
  {
    id: 'cat-5',
    name: 'Jewelry',
    slug: 'jewelry',
    iconName: 'Gem',
    productCount: 1800,
    gradient: 'from-violet-100 to-purple-50',
    iconColor: 'text-violet-500',
  },
  {
    id: 'cat-6',
    name: 'Electronics',
    slug: 'electronics',
    iconName: 'Smartphone',
    productCount: 960,
    gradient: 'from-slate-100 to-slate-50',
    iconColor: 'text-slate-500',
  },
  {
    id: 'cat-7',
    name: 'Kids & Toys',
    slug: 'kids-toys',
    iconName: 'Baby',
    productCount: 1340,
    gradient: 'from-orange-100 to-orange-50',
    iconColor: 'text-orange-500',
  },
  {
    id: 'cat-8',
    name: 'Kitchen',
    slug: 'kitchen',
    iconName: 'UtensilsCrossed',
    productCount: 1680,
    gradient: 'from-lime-100 to-lime-50',
    iconColor: 'text-lime-600',
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Elegant Floral Maxi Dress',
    slug: 'elegant-floral-maxi-dress',
    price: 89.99,
    compareAtPrice: 149.99,
    images: [
      'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.7,
    reviewCount: 248,
    category: 'womens-fashion',
    categoryLabel: "Women's Fashion",
    badge: 'SALE',
    variants: [
      { id: 'v1', name: 'Blue / Small', color: 'Blue', size: 'Small', price: 89.99, inStock: true },
      { id: 'v2', name: 'Blue / Medium', color: 'Blue', size: 'Medium', price: 89.99, inStock: true },
      { id: 'v3', name: 'Pink / Small', color: 'Pink', size: 'Small', price: 89.99, inStock: false },
    ],
    description: 'Flowing maxi dress with delicate floral print, perfect for summer events and casual outings. Made from breathable cotton blend fabric with adjustable waist tie.',
    shippingDays: '3-5 days',
    warehouse: 'US',
    inStock: true,
    stockCount: 45,
  },
  {
    id: 'prod-2',
    name: 'Premium Leather Crossbody Bag',
    slug: 'premium-leather-crossbody-bag',
    price: 124.99,
    compareAtPrice: null,
    images: [
      'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.9,
    reviewCount: 412,
    category: 'womens-fashion',
    categoryLabel: "Women's Fashion",
    badge: 'BESTSELLER',
    variants: [
      { id: 'v4', name: 'Black', color: 'Black', price: 124.99, inStock: true },
      { id: 'v5', name: 'Brown', color: 'Brown', price: 124.99, inStock: true },
      { id: 'v6', name: 'Tan', color: 'Tan', price: 124.99, inStock: true },
    ],
    description: 'Handcrafted genuine leather crossbody bag with adjustable strap, multiple compartments, and antique brass hardware. Timeless design that complements any outfit.',
    shippingDays: '2-5 days',
    warehouse: 'US',
    inStock: true,
    stockCount: 28,
  },
  {
    id: 'prod-3',
    name: 'Wireless Pet Water Fountain',
    slug: 'wireless-pet-water-fountain',
    price: 42.99,
    compareAtPrice: 69.99,
    images: [
      'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.6,
    reviewCount: 892,
    category: 'pet-supplies',
    categoryLabel: 'Pet Supplies',
    badge: 'TRENDING',
    variants: [],
    description: 'Ultra-quiet automatic pet water fountain with 2L capacity, triple filtration system, and energy-efficient pump. Keeps water fresh and encourages pets to drink more.',
    shippingDays: '7-12 days',
    warehouse: 'CN',
    inStock: true,
    stockCount: 156,
  },
  {
    id: 'prod-4',
    name: 'Orthopedic Pet Bed with Memory Foam',
    slug: 'orthopedic-pet-bed-memory-foam',
    price: 79.99,
    compareAtPrice: null,
    images: [
      'https://images.pexels.com/photos/4587998/pexels-photo-4587998.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.8,
    reviewCount: 623,
    category: 'pet-supplies',
    categoryLabel: 'Pet Supplies',
    badge: 'BESTSELLER',
    variants: [
      { id: 'v7', name: 'Medium - Gray', size: 'Medium', color: 'Gray', price: 79.99, inStock: true },
      { id: 'v8', name: 'Large - Gray', size: 'Large', color: 'Gray', price: 99.99, inStock: true },
      { id: 'v9', name: 'Large - Brown', size: 'Large', color: 'Brown', price: 99.99, inStock: true },
    ],
    description: 'Premium orthopedic pet bed with high-density memory foam base and removable, machine-washable cover. Provides superior joint support for pets of all ages.',
    shippingDays: '2-5 days',
    warehouse: 'US',
    inStock: true,
    stockCount: 34,
  },
  {
    id: 'prod-5',
    name: 'Modern Ceramic Planter Set',
    slug: 'modern-ceramic-planter-set',
    price: 54.99,
    compareAtPrice: 89.99,
    images: [
      'https://images.pexels.com/photos/6208086/pexels-photo-6208086.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/4505168/pexels-photo-4505168.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.5,
    reviewCount: 178,
    category: 'home-garden',
    categoryLabel: 'Home & Garden',
    badge: 'NEW',
    variants: [],
    description: 'Set of 3 handcrafted ceramic planters with drainage holes and bamboo saucers. Minimalist design perfect for succulents, herbs, and small houseplants.',
    shippingDays: '5-9 days',
    warehouse: 'CN',
    inStock: true,
    stockCount: 67,
  },
  {
    id: 'prod-6',
    name: 'Himalayan Salt Lamp - Large',
    slug: 'himalayan-salt-lamp-large',
    price: 39.99,
    compareAtPrice: null,
    images: [
      'https://images.pexels.com/photos/4588047/pexels-photo-4588047.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.7,
    reviewCount: 1024,
    category: 'home-garden',
    categoryLabel: 'Home & Garden',
    badge: 'TRENDING',
    variants: [],
    description: 'Authentic Himalayan salt lamp carved from natural crystal salt. Creates warm ambient lighting and may help purify air. Includes dimmable cord and wooden base.',
    shippingDays: '7-10 days',
    warehouse: 'CN',
    inStock: true,
    stockCount: 203,
  },
  {
    id: 'prod-7',
    name: 'Velvet Throw Pillow Covers - Set of 4',
    slug: 'velvet-throw-pillow-covers-set',
    price: 32.99,
    compareAtPrice: 59.99,
    images: [
      'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.4,
    reviewCount: 567,
    category: 'home-garden',
    categoryLabel: 'Home & Garden',
    badge: 'SALE',
    variants: [
      { id: 'v10', name: 'Navy Blue', color: 'Navy', price: 32.99, inStock: true },
      { id: 'v11', name: 'Emerald Green', color: 'Green', price: 32.99, inStock: true },
      { id: 'v12', name: 'Dusty Rose', color: 'Pink', price: 32.99, inStock: false },
    ],
    description: 'Luxurious velvet pillow covers with hidden zipper closure. Set of 4 covers in coordinating colors. Soft, durable fabric that adds instant elegance to any room.',
    shippingDays: '7-12 days',
    warehouse: 'CN',
    inStock: true,
    stockCount: 89,
  },
  {
    id: 'prod-8',
    name: 'Vitamin C Serum with Hyaluronic Acid',
    slug: 'vitamin-c-serum-hyaluronic-acid',
    price: 28.99,
    compareAtPrice: null,
    images: [
      'https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.8,
    reviewCount: 2156,
    category: 'health-beauty',
    categoryLabel: 'Health & Beauty',
    badge: 'BESTSELLER',
    variants: [],
    description: 'Professional-grade vitamin C serum with 20% concentration, hyaluronic acid, and vitamin E. Brightens skin, reduces fine lines, and boosts collagen production.',
    shippingDays: '3-5 days',
    warehouse: 'US',
    inStock: true,
    stockCount: 412,
  },
  {
    id: 'prod-9',
    name: 'Jade Roller & Gua Sha Set',
    slug: 'jade-roller-gua-sha-set',
    price: 19.99,
    compareAtPrice: 39.99,
    images: [
      'https://images.pexels.com/photos/4465124/pexels-photo-4465124.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.6,
    reviewCount: 892,
    category: 'health-beauty',
    categoryLabel: 'Health & Beauty',
    badge: 'SALE',
    variants: [],
    description: 'Natural jade stone facial roller and gua sha tool set. Promotes lymphatic drainage, reduces puffiness, and enhances product absorption. Includes storage pouch.',
    shippingDays: '7-12 days',
    warehouse: 'CN',
    inStock: true,
    stockCount: 234,
  },
  {
    id: 'prod-10',
    name: 'Aromatherapy Essential Oil Diffuser',
    slug: 'aromatherapy-essential-oil-diffuser',
    price: 34.99,
    compareAtPrice: null,
    images: [
      'https://images.pexels.com/photos/4505168/pexels-photo-4505168.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.7,
    reviewCount: 1456,
    category: 'health-beauty',
    categoryLabel: 'Health & Beauty',
    badge: 'TRENDING',
    variants: [
      { id: 'v13', name: 'White Oak', color: 'White', price: 34.99, inStock: true },
      { id: 'v14', name: 'Dark Walnut', color: 'Brown', price: 34.99, inStock: true },
    ],
    description: 'Ultrasonic essential oil diffuser with 300ml capacity, 7 LED color options, and auto shut-off. Whisper-quiet operation with multiple mist settings.',
    shippingDays: '5-8 days',
    warehouse: 'CN',
    inStock: true,
    stockCount: 178,
  },
  {
    id: 'prod-11',
    name: 'Dainty Gold Layered Necklace Set',
    slug: 'dainty-gold-layered-necklace-set',
    price: 44.99,
    compareAtPrice: 79.99,
    images: [
      'https://images.pexels.com/photos/1458695/pexels-photo-1458695.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.5,
    reviewCount: 324,
    category: 'jewelry',
    categoryLabel: 'Jewelry',
    badge: 'NEW',
    variants: [
      { id: 'v15', name: 'Gold', color: 'Gold', price: 44.99, inStock: true },
      { id: 'v16', name: 'Silver', color: 'Silver', price: 44.99, inStock: true },
      { id: 'v17', name: 'Rose Gold', color: 'Rose Gold', price: 44.99, inStock: true },
    ],
    description: 'Set of 3 delicate layered necklaces with varying lengths. 14K gold plated over sterling silver. Features coin, bar, and stone pendants. Waterproof and tarnish-resistant.',
    shippingDays: '7-12 days',
    warehouse: 'CN',
    inStock: true,
    stockCount: 145,
  },
  {
    id: 'prod-12',
    name: 'Crystal Drop Earrings',
    slug: 'crystal-drop-earrings',
    price: 29.99,
    compareAtPrice: null,
    images: [
      'https://images.pexels.com/photos/1454171/pexels-photo-1454171.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.8,
    reviewCount: 567,
    category: 'jewelry',
    categoryLabel: 'Jewelry',
    badge: 'BESTSELLER',
    variants: [],
    description: 'Elegant teardrop crystal earrings with rhodium plating. Hypoallergenic posts suitable for sensitive ears. Sparkles beautifully in any lighting.',
    shippingDays: '7-10 days',
    warehouse: 'CN',
    inStock: true,
    stockCount: 267,
  },
  {
    id: 'prod-13',
    name: 'Wireless Bluetooth Earbuds Pro',
    slug: 'wireless-bluetooth-earbuds-pro',
    price: 79.99,
    compareAtPrice: 129.99,
    images: [
      'https://images.pexels.com/photos/3825517/pexels-photo-3825517.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.6,
    reviewCount: 1834,
    category: 'electronics',
    categoryLabel: 'Electronics',
    badge: 'SALE',
    variants: [
      { id: 'v18', name: 'Black', color: 'Black', price: 79.99, inStock: true },
      { id: 'v19', name: 'White', color: 'White', price: 79.99, inStock: true },
    ],
    description: 'Premium wireless earbuds with active noise cancellation, 30-hour battery life, and IPX7 waterproof rating. Crystal clear calls and deep bass response.',
    shippingDays: '3-5 days',
    warehouse: 'US',
    inStock: true,
    stockCount: 89,
  },
  {
    id: 'prod-14',
    name: 'Smart Watch with Fitness Tracker',
    slug: 'smart-watch-fitness-tracker',
    price: 149.99,
    compareAtPrice: null,
    images: [
      'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.7,
    reviewCount: 2341,
    category: 'electronics',
    categoryLabel: 'Electronics',
    badge: 'TRENDING',
    variants: [
      { id: 'v20', name: 'Black / Small', color: 'Black', size: 'Small', price: 149.99, inStock: true },
      { id: 'v21', name: 'Black / Large', color: 'Black', size: 'Large', price: 149.99, inStock: true },
      { id: 'v22', name: 'Rose Gold / Small', color: 'Rose Gold', size: 'Small', price: 149.99, inStock: true },
    ],
    description: 'Advanced fitness smartwatch with heart rate monitor, sleep tracking, GPS, and 50+ sport modes. Compatible with iOS and Android. 7-day battery life.',
    shippingDays: '2-5 days',
    warehouse: 'US',
    inStock: true,
    stockCount: 56,
  },
  {
    id: 'prod-15',
    name: 'Educational STEM Building Blocks Set',
    slug: 'educational-stem-building-blocks-set',
    price: 49.99,
    compareAtPrice: null,
    images: [
      'https://images.pexels.com/photos/1319572/pexels-photo-1319572.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.9,
    reviewCount: 1245,
    category: 'kids-toys',
    categoryLabel: 'Kids & Toys',
    badge: 'BESTSELLER',
    variants: [],
    description: '520-piece building blocks set designed to enhance creativity, problem-solving, and motor skills. Compatible with major brands. Includes storage container and idea booklet.',
    shippingDays: '3-5 days',
    warehouse: 'US',
    inStock: true,
    stockCount: 123,
  },
  {
    id: 'prod-16',
    name: 'Plush Unicorn Stuffed Animal',
    slug: 'plush-unicorn-stuffed-animal',
    price: 24.99,
    compareAtPrice: 39.99,
    images: [
      'https://images.pexels.com/photos/2287310/pexels-photo-2287310.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.8,
    reviewCount: 892,
    category: 'kids-toys',
    categoryLabel: 'Kids & Toys',
    badge: 'TRENDING',
    variants: [
      { id: 'v23', name: 'Small (12")', size: 'Small', price: 24.99, inStock: true },
      { id: 'v24', name: 'Large (18")', size: 'Large', price: 34.99, inStock: true },
    ],
    description: 'Super soft plush unicorn with rainbow mane and tail. Made from hypoallergenic materials, machine washable. Perfect cuddle companion for all ages.',
    shippingDays: '5-8 days',
    warehouse: 'CN',
    inStock: true,
    stockCount: 234,
  },
  {
    id: 'prod-17',
    name: 'Stainless Steel Knife Set - 15 Pieces',
    slug: 'stainless-steel-knife-set-15-pieces',
    price: 89.99,
    compareAtPrice: 149.99,
    images: [
      'https://images.pexels.com/photos/2291599/pexels-photo-2291599.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.7,
    reviewCount: 678,
    category: 'kitchen',
    categoryLabel: 'Kitchen',
    badge: 'SALE',
    variants: [],
    description: 'Professional-grade 15-piece knife set with high-carbon stainless steel blades, ergonomic handles, and bamboo block. Includes knife sharpener and kitchen shears.',
    shippingDays: '2-5 days',
    warehouse: 'US',
    inStock: true,
    stockCount: 67,
  },
  {
    id: 'prod-18',
    name: 'Cast Iron Skillet - Pre-Seasoned',
    slug: 'cast-iron-skillet-pre-seasoned',
    price: 39.99,
    compareAtPrice: null,
    images: [
      'https://images.pexels.com/photos/6412691/pexels-photo-6412691.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.9,
    reviewCount: 1567,
    category: 'kitchen',
    categoryLabel: 'Kitchen',
    badge: 'BESTSELLER',
    variants: [
      { id: 'v25', name: '10 inch', size: '10"', price: 39.99, inStock: true },
      { id: 'v26', name: '12 inch', size: '12"', price: 49.99, inStock: true },
    ],
    description: 'Premium pre-seasoned cast iron skillet with helper handle. Naturally non-stick, oven-safe to 500°F, and works on all cooktops including induction.',
    shippingDays: '3-5 days',
    warehouse: 'US',
    inStock: true,
    stockCount: 145,
  },
  {
    id: 'prod-19',
    name: 'Silicone Baking Mat Set',
    slug: 'silicone-baking-mat-set',
    price: 16.99,
    compareAtPrice: 29.99,
    images: [
      'https://images.pexels.com/photos/4686832/pexels-photo-4686832.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.6,
    reviewCount: 534,
    category: 'kitchen',
    categoryLabel: 'Kitchen',
    badge: 'NEW',
    variants: [],
    description: 'Set of 3 professional-grade silicone baking mats. Non-stick, reusable, and dishwasher safe. Heat resistant up to 480°F. Replaces parchment paper and reduces waste.',
    shippingDays: '7-10 days',
    warehouse: 'CN',
    inStock: true,
    stockCount: 289,
  },
  {
    id: 'prod-20',
    name: 'Minimalist Wall Art Canvas - Set of 3',
    slug: 'minimalist-wall-art-canvas-set',
    price: 64.99,
    compareAtPrice: 99.99,
    images: [
      'https://images.pexels.com/photos/1974596/pexels-photo-1974596.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    rating: 4.5,
    reviewCount: 423,
    category: 'home-garden',
    categoryLabel: 'Home & Garden',
    badge: 'TRENDING',
    variants: [],
    description: 'Set of 3 abstract canvas prints with minimalist design. Museum-quality giclée printing on premium canvas with gallery-wrapped edges. Ready to hang.',
    shippingDays: '5-9 days',
    warehouse: 'CN',
    inStock: true,
    stockCount: 78,
  },
];

export const flashDeals: Product[] = [
  products[0],
  products[8],
  products[12],
];

export const reviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    authorName: 'Sarah M.',
    rating: 5,
    date: '2026-01-28',
    title: 'Perfect summer dress!',
    body: 'This dress exceeded my expectations. The fabric is lightweight and breathable, perfect for hot summer days. The floral print is even prettier in person. I ordered my usual size and it fits perfectly.',
    verified: true,
  },
  {
    id: 'rev-2',
    productId: 'prod-2',
    authorName: 'Jennifer L.',
    rating: 5,
    date: '2026-02-05',
    title: 'Best bag I\'ve ever owned',
    body: 'The quality of this leather is outstanding. It\'s the perfect size for daily use - fits my wallet, phone, keys, and a small water bottle. The adjustable strap is comfortable and the color is beautiful.',
    verified: true,
  },
  {
    id: 'rev-3',
    productId: 'prod-3',
    authorName: 'Mike R.',
    rating: 5,
    date: '2026-01-15',
    title: 'My cats love it!',
    body: 'Both of my cats were drinking from it within an hour of setting it up. It\'s very quiet and the LED light at night is a nice touch. Easy to clean and the filters are readily available.',
    verified: true,
  },
  {
    id: 'rev-4',
    productId: 'prod-4',
    authorName: 'Rachel K.',
    rating: 5,
    date: '2026-02-01',
    title: 'Game changer for my senior dog',
    body: 'My 12-year-old lab has arthritis and this bed has made such a difference. He sleeps through the night now and seems much more comfortable. The memory foam is thick and supportive.',
    verified: true,
  },
  {
    id: 'rev-5',
    productId: 'prod-8',
    authorName: 'Amanda P.',
    rating: 5,
    date: '2026-01-20',
    title: 'Visible results in 2 weeks!',
    body: 'I\'ve been using this serum every morning for two weeks and I can already see a difference. My skin looks brighter and more even-toned. It absorbs quickly and doesn\'t feel sticky.',
    verified: true,
  },
  {
    id: 'rev-6',
    productId: 'prod-13',
    authorName: 'David T.',
    rating: 4,
    date: '2026-02-08',
    title: 'Great sound quality',
    body: 'These earbuds sound amazing and the noise cancellation works really well. Battery life is excellent. Only minor complaint is the fit - took me a while to find the right ear tips.',
    verified: true,
  },
  {
    id: 'rev-7',
    productId: 'prod-14',
    authorName: 'Lisa H.',
    rating: 5,
    date: '2026-01-25',
    title: 'Perfect fitness companion',
    body: 'This watch has everything I need to track my workouts and health. The heart rate monitor is accurate, GPS works great, and I love getting notifications on my wrist. Battery lasts almost 8 days for me.',
    verified: true,
  },
  {
    id: 'rev-8',
    productId: 'prod-15',
    authorName: 'Tom W.',
    rating: 5,
    date: '2026-02-10',
    title: 'Kids can\'t put it down',
    body: 'Bought this for my 7-year-old son and he\'s been building non-stop. The pieces are high quality and compatible with our existing blocks. Great value for the number of pieces you get.',
    verified: true,
  },
  {
    id: 'rev-9',
    productId: 'prod-17',
    authorName: 'Christine B.',
    rating: 5,
    date: '2026-01-30',
    title: 'Professional quality at home',
    body: 'These knives are incredibly sharp and well-balanced. The block is beautiful and keeps them organized. Came with a sharpener which is a nice bonus. Feels like a professional kitchen now!',
    verified: true,
  },
  {
    id: 'rev-10',
    productId: 'prod-18',
    authorName: 'Mark S.',
    rating: 5,
    date: '2026-02-03',
    title: 'Cast iron perfection',
    body: 'This skillet is a workhorse. Already perfectly seasoned out of the box. I use it almost daily for everything from eggs to steaks. Heats evenly and the helper handle makes it easy to maneuver.',
    verified: true,
  },
];
