export const SUBCATEGORY_TAGS: Record<string, string[]> = {
  fashion: ['Tops', 'Dresses', 'Outerwear', 'Bags & Accessories', 'Swimwear', 'Shoes', 'Activewear'],
  'health-beauty': [
    'Skincare',
    'Haircare',
    'Makeup',
    'Wellness',
    'Oral Care',
    'Body Care',
    'Tools & Devices',
  ],
  'pet-supplies': [
    'Dog',
    'Cat',
    'Fish & Aquarium',
    'Birds',
    'Small Animals',
    'Beds & Furniture',
    'Toys & Treats',
  ],
  jewelry: ['Necklaces', 'Earrings', 'Rings', 'Bracelets', 'Pendants', 'Sets', "Men's Jewelry"],
  'home-furniture': [
    'Living Room',
    'Bedroom',
    'Bathroom',
    'Lighting',
    'Decor',
    'Bedding & Textiles',
    'Cleaning',
  ],
  'garden-outdoor': [
    'Patio Furniture',
    'Planters & Pots',
    'Grills & BBQ',
    'Gazebos & Canopies',
    'Lawn Care',
    'Outdoor Lighting',
    'Pool & Spa',
  ],
  'kitchen-dining': [
    'Cookware',
    'Bakeware',
    'Knives & Tools',
    'Small Appliances',
    'Dinnerware',
    'Food Storage',
    'Coffee & Tea',
  ],
  electronics: [
    'Audio',
    'Phone Accessories',
    'Charging & Cables',
    'Smart Home',
    'Cameras',
    'Computer Accessories',
    'Gaming',
  ],
  'kids-toys': [
    'Educational',
    'Building & Construction',
    'Dolls & Figures',
    'Outdoor Play',
    'Baby Gear',
    'Arts & Crafts',
    'Ride-On',
  ],
  'storage-organization': [
    'Closet',
    'Shelving',
    'Bins & Baskets',
    'Garage Storage',
    'Kitchen Organization',
    'Bathroom Organization',
    'Laundry',
  ],
  'tools-hardware': [
    'Power Tools',
    'Hand Tools',
    'Automotive',
    'Plumbing',
    'Electrical',
    'Painting',
    'Safety & PPE',
  ],
  'sports-outdoors': [
    'Fitness & Gym',
    'Camping & Hiking',
    'Fishing',
    'Cycling',
    'Team Sports',
    'Water Sports',
    'Outdoor Recreation',
  ],
};

export const TAG_KEYWORDS: Record<string, string[]> = {
  Tops: ['top', 'shirt', 'blouse', 'tee', 't-shirt', 'tank', 'camisole', 'crop top', 'tunic'],
  Dresses: ['dress', 'gown', 'maxi', 'midi', 'mini', 'sundress'],
  Outerwear: ['jacket', 'coat', 'parka', 'blazer', 'cardigan', 'vest', 'windbreaker', 'trench'],
  'Bags & Accessories': [
    'bag',
    'handbag',
    'tote',
    'backpack',
    'purse',
    'crossbody',
    'wallet',
    'belt',
    'hat',
    'scarf',
    'sunglass',
    'glove',
    'watch band',
  ],
  Swimwear: ['swim', 'swimwear', 'bikini', 'one-piece', 'swimsuit', 'trunks', 'rash guard'],
  Shoes: ['shoe', 'sneaker', 'boot', 'heel', 'slipper', 'sandal', 'loafer'],
  Activewear: ['active', 'sport', 'gym', 'yoga', 'workout', 'athletic', 'running', 'legging'],
  Skincare: ['skincare', 'skin', 'serum', 'cream', 'cleanser', 'moisturizer', 'mask', 'lotion', 'toner'],
  Haircare: [
    'hair',
    'shampoo',
    'conditioner',
    'hair oil',
    'hair mask',
    'wig',
    'hair dryer',
    'curling',
    'straightener',
  ],
  Makeup: ['makeup', 'lipstick', 'foundation', 'eyeshadow', 'mascara', 'blush', 'concealer', 'brow'],
  Wellness: ['wellness', 'supplement', 'vitamin', 'sleep', 'relax', 'aroma', 'essential oil'],
  'Oral Care': ['oral', 'toothbrush', 'toothpaste', 'floss', 'whitening', 'mouth'],
  'Body Care': ['body', 'body wash', 'soap', 'deodorant', 'lotion', 'scrub', 'shower gel'],
  'Tools & Devices': ['device', 'tool', 'massager', 'roller', 'gua sha', 'steamer', 'trimmer', 'shaver', 'epilator'],
  Dog: ['dog', 'puppy', 'canine'],
  Cat: ['cat', 'kitten', 'feline'],
  'Fish & Aquarium': ['fish', 'aquarium', 'tank', 'filter', 'aquatic'],
  Birds: ['bird', 'parrot', 'cage', 'feeder'],
  'Small Animals': ['hamster', 'rabbit', 'guinea', 'ferret', 'small animal'],
  'Beds & Furniture': ['bed', 'mat', 'cushion', 'pet bed', 'cat tree', 'scratch', 'sofa'],
  'Toys & Treats': ['toy', 'chew', 'ball', 'treat', 'snack', 'interactive'],
  Necklaces: ['necklace', 'necklaces', 'chain', 'choker'],
  Earrings: ['earring', 'earrings', 'ear stud', 'ear cuff', 'ear clip', 'hoop'],
  Rings: ['ring', 'rings', 'band'],
  Bracelets: ['bracelet', 'bracelets', 'bangle', 'cuff', 'wristband'],
  Pendants: ['pendant', 'locket'],
  Sets: ['set', 'bundle', 'collection'],
  "Men's Jewelry": ['men', 'mens', 'male', 'boy', 'signet', 'cufflink'],
  'Living Room': ['sofa', 'couch', 'sectional', 'coffee table', 'tv stand', 'console table', 'recliner', 'armchair'],
  Bedroom: ['bed', 'bed frame', 'headboard', 'nightstand', 'dresser', 'wardrobe', 'bedding set'],
  Bathroom: ['bath', 'bathroom', 'shower', 'toilet', 'towel', 'bath mat', 'soap', 'sink'],
  Lighting: ['lamp', 'light', 'led', 'chandelier', 'sconce', 'bulb', 'ceiling light'],
  Decor: ['decor', 'wall art', 'canvas', 'vase', 'rug', 'pillow', 'curtain', 'mirror', 'frame', 'statue'],
  'Bedding & Textiles': ['bedding', 'duvet', 'comforter', 'sheet', 'pillowcase', 'blanket', 'quilt', 'throw'],
  Cleaning: ['clean', 'cleaning', 'vacuum', 'mop', 'broom', 'sponge', 'detergent'],
  'Patio Furniture': ['patio', 'outdoor chair', 'outdoor table', 'patio set', 'bench', 'lounger'],
  'Planters & Pots': ['planter', 'pot', 'flower pot', 'garden pot', 'urn', 'raised bed'],
  'Grills & BBQ': ['grill', 'bbq', 'barbecue', 'smoker', 'charcoal'],
  'Gazebos & Canopies': ['gazebo', 'canopy', 'pergola', 'awning', 'carport'],
  'Lawn Care': ['lawn', 'mower', 'trimmer', 'rake', 'shovel', 'leaf', 'hedge'],
  'Outdoor Lighting': ['solar light', 'outdoor light', 'pathway', 'lantern', 'string light'],
  'Pool & Spa': ['pool', 'spa', 'hot tub', 'inflatable pool', 'float', 'filter'],
  Cookware: ['pan', 'pot', 'skillet', 'cookware', 'casserole', 'wok'],
  Bakeware: ['bake', 'baking', 'tray', 'sheet', 'muffin', 'cake', 'cookie'],
  'Knives & Tools': ['knife', 'knives', 'cleaver', 'cutting board', 'peeler', 'grater', 'tongs', 'spatula'],
  'Small Appliances': [
    'appliance',
    'blender',
    'mixer',
    'toaster',
    'kettle',
    'microwave',
    'air fryer',
    'coffee maker',
  ],
  Dinnerware: ['plate', 'bowl', 'dinnerware', 'cutlery', 'utensil set', 'dish'],
  'Food Storage': ['storage', 'container', 'lunch box', 'food storage', 'seal', 'jar'],
  'Coffee & Tea': ['coffee', 'tea', 'teapot', 'mug', 'kettle', 'espresso'],
  Audio: ['audio', 'headphone', 'earbud', 'speaker', 'sound', 'microphone'],
  'Phone Accessories': ['phone', 'case', 'screen protector', 'magnet', 'holder', 'stand', 'ring'],
  'Charging & Cables': ['charger', 'charging', 'cable', 'adapter', 'power bank', 'usb'],
  'Smart Home': ['smart', 'sensor', 'wifi', 'automation', 'hub', 'assistant', 'camera'],
  Cameras: ['camera', 'lens', 'tripod', 'gimbal', 'photography'],
  'Computer Accessories': ['computer', 'laptop', 'keyboard', 'mouse', 'monitor', 'webcam', 'desk'],
  Gaming: ['game', 'gaming', 'console', 'controller', 'mouse', 'keyboard'],
  Educational: ['educational', 'learning', 'stem', 'puzzle', 'study', 'science kit'],
  'Building & Construction': ['building', 'block', 'lego', 'construction', 'model kit'],
  'Dolls & Figures': ['doll', 'figure', 'action figure', 'plush', 'stuffed'],
  'Outdoor Play': ['outdoor', 'play', 'swing', 'slide', 'sandbox', 'playhouse'],
  'Baby Gear': ['baby', 'infant', 'crib', 'stroller', 'high chair', 'diaper', 'baby gate'],
  'Arts & Crafts': ['craft', 'coloring', 'paint', 'art', 'sticker', 'diy'],
  'Ride-On': ['ride-on', 'ride on', 'scooter', 'balance bike', 'ride'],
  Closet: ['closet', 'wardrobe', 'hanger', 'garment', 'shoe rack'],
  Shelving: ['shelf', 'shelving', 'bookcase', 'display shelf'],
  'Bins & Baskets': ['bin', 'basket', 'storage box', 'container'],
  'Garage Storage': ['garage', 'tool chest', 'pegboard', 'rack', 'workbench'],
  'Kitchen Organization': ['pantry', 'spice rack', 'drawer organizer', 'kitchen organizer'],
  'Bathroom Organization': ['bathroom organizer', 'caddy', 'shower caddy', 'toiletry'],
  Laundry: ['laundry', 'hamper', 'drying rack', 'ironing board'],
  'Power Tools': ['drill', 'saw', 'sander', 'grinder', 'jigsaw', 'power tool'],
  'Hand Tools': ['wrench', 'screwdriver', 'hammer', 'pliers', 'tool set'],
  Automotive: ['car', 'auto', 'automotive', 'vehicle', 'tire', 'headlight'],
  Plumbing: ['plumbing', 'faucet', 'pipe', 'drain', 'toilet', 'valve'],
  Electrical: ['electrical', 'wire', 'socket', 'outlet', 'switch', 'voltage'],
  Painting: ['paint', 'primer', 'brush', 'roller', 'tape'],
  'Safety & PPE': ['safety', 'glove', 'goggles', 'mask', 'helmet', 'ppe'],
  'Fitness & Gym': ['fitness', 'exercise', 'gym', 'dumbbell', 'yoga', 'workout', 'treadmill'],
  'Camping & Hiking': ['camping', 'tent', 'sleeping bag', 'hiking', 'backpack', 'lantern'],
  Fishing: ['fishing', 'rod', 'reel', 'bait', 'tackle'],
  Cycling: ['cycling', 'bicycle', 'bike', 'helmet', 'bike rack'],
  'Team Sports': ['soccer', 'basketball', 'football', 'baseball', 'volleyball', 'team sport'],
  'Water Sports': ['swim', 'swimming', 'snorkel', 'paddle', 'kayak', 'water'],
  'Outdoor Recreation': ['outdoor', 'recreation', 'hammock', 'climbing', 'skateboard', 'scooter'],
};
