/**
 * recategorize-all.js
 * Recategorize all active products into 12 categories.
 * Usage: node scripts/recategorize-all.js [--apply]
 */
const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '..', '.env.local');
const envContent = fs.readFileSync(envPath, 'utf-8');
const env = {};
envContent.split('\n').forEach((line) => {
  const eq = line.indexOf('=');
  if (eq > 0) {
    const key = line.substring(0, eq).trim();
    const val = line.substring(eq + 1).trim();
    if (key && val) env[key] = val;
  }
});

const SUPABASE_URL = env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_KEY = env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local');
  console.error('Found keys:', Object.keys(env).join(', '));
  process.exit(1);
}

const APPLY = process.argv.includes('--apply');

async function supabaseGet(table, params = '') {
  const url = `${SUPABASE_URL}/rest/v1/${table}?${params}`;
  const res = await fetch(url, {
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` },
  });
  if (!res.ok) throw new Error(`GET ${table} failed (${res.status}): ${await res.text()}`);
  return res.json();
}

async function supabasePatch(table, filter, body) {
  const url = `${SUPABASE_URL}/rest/v1/${table}?${filter}`;
  const res = await fetch(url, {
    method: 'PATCH',
    headers: {
      apikey: SUPABASE_KEY,
      Authorization: `Bearer ${SUPABASE_KEY}`,
      'Content-Type': 'application/json',
      Prefer: 'return=representation',
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`PATCH ${table} failed (${res.status}): ${await res.text()}`);
  return res.json();
}

async function supabaseInsert(table, body) {
  const url = `${SUPABASE_URL}/rest/v1/${table}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      apikey: SUPABASE_KEY,
      Authorization: `Bearer ${SUPABASE_KEY}`,
      'Content-Type': 'application/json',
      Prefer: 'return=representation',
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`POST ${table} failed (${res.status}): ${await res.text()}`);
  return res.json();
}

async function supabaseDelete(table, filter) {
  const url = `${SUPABASE_URL}/rest/v1/${table}?${filter}`;
  const res = await fetch(url, {
    method: 'DELETE',
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` },
  });
  if (!res.ok) throw new Error(`DELETE ${table} failed (${res.status}): ${await res.text()}`);
}

const TARGET_CATEGORIES = [
  { name: 'Fashion', slug: 'fashion' },
  { name: 'Health & Beauty', slug: 'health-beauty' },
  { name: 'Pet Supplies', slug: 'pet-supplies' },
  { name: 'Jewelry', slug: 'jewelry' },
  { name: 'Home & Furniture', slug: 'home-furniture' },
  { name: 'Garden & Outdoor', slug: 'garden-outdoor' },
  { name: 'Kitchen & Dining', slug: 'kitchen-dining' },
  { name: 'Electronics', slug: 'electronics' },
  { name: 'Kids & Toys', slug: 'kids-toys' },
  { name: 'Storage & Organization', slug: 'storage-organization' },
  { name: 'Tools & Hardware', slug: 'tools-hardware' },
  { name: 'Sports & Outdoors', slug: 'sports-outdoors' },
];

const CATEGORY_KEYWORDS = [
  {
    slug: 'pet-supplies',
    name: 'Pet Supplies',
    keywords: [
      'pet',
      'dog',
      'cat',
      'puppy',
      'kitten',
      'aquarium',
      'fish tank',
      'bird cage',
      'hamster',
      'rabbit',
      'leash',
      'collar',
      'kennel',
      'litter',
      'chew toy',
      'scratching',
      'pet bed',
      'pet bowl',
      'pet feeder',
      'terrarium',
      'reptile',
    ],
  },
  {
    slug: 'kids-toys',
    name: 'Kids & Toys',
    keywords: [
      'toy',
      'kids',
      'children',
      'baby',
      'infant',
      'toddler',
      'playhouse',
      'playground',
      'stroller',
      'crib',
      'diaper',
      'pacifier',
      'nursery',
      'doll',
      'puzzle',
      'building block',
      'lego',
      'stuffed animal',
      'bouncer',
      'rocking horse',
      'play mat',
      'teething',
      'baby monitor',
      'building toy',
      'model kit',
      'DIY kit',
      'craft set',
      'puzzle toy',
      'jigsaw',
      'magnetic tile',
      'train set',
      'race track',
      'slot car',
      'robot toy',
      'dinosaur toy',
      'action figure',
      'superhero toy',
      'princess toy',
      'dress up',
      'costume kids',
      'play kitchen',
      'play tool',
      'play doctor',
      'sand toy',
      'bubble',
      'water toy',
      'ride on',
      'balance bike',
      'tricycle',
      'wagon kid',
      'drum set kid',
      'musical toy',
      'xylophone',
      'keyboard kid',
    ],
  },
  {
    slug: 'electronics',
    name: 'Electronics',
    keywords: [
      'bluetooth',
      'wireless',
      'USB',
      'charger',
      'speaker',
      'headphone',
      'earphone',
      'earbud',
      'smartwatch',
      'phone case',
      'phone mount',
      'tablet',
      'camera',
      'drone',
      'remote control',
      'HDMI',
      'adapter',
      'power bank',
      'screen protector',
      'keyboard',
      'mouse',
      'gaming',
      'controller',
      'console',
      'VR',
      'projector',
      'security camera',
      'webcam',
      'microphone',
      'antenna',
      'router',
      'GPS',
      'dashcam',
      'headset',
      'headphone',
      'earpiece',
      'charger',
      'charging',
      'magnetic suction',
      'phone case',
      'phone card',
      'mobile phone',
      'phone stand',
      'phone mount',
      'phone holder',
      'tablet stand',
      'USB',
      'Type C',
      'Lightning',
      'HDMI',
      'cable cord',
      'power adapter',
      'LED strip',
      'LED light',
      'smart home',
      'smart plug',
      'ring doorbell',
      'trail camera',
      'action camera',
      'memory card',
      'SD card',
      'flash drive',
      'hard drive',
      'SSD',
      'monitor',
      'display screen',
      'printer',
      'scanner',
      'radio',
      'walkie talkie',
      'intercom',
      'satellite',
      'signal booster',
      'Wi-Fi',
      'ethernet',
      'modem',
      'hub',
    ],
  },
  {
    slug: 'jewelry',
    name: 'Jewelry',
    keywords: [
      'necklace',
      'bracelet',
      'earring',
      'ring',
      'pendant',
      'anklet',
      'brooch',
      'jewelry box',
      'bead',
      'charm',
      'chain',
      'gemstone',
      'crystal',
      'sterling silver',
      'gold plated',
      'titanium ring',
      'cufflink',
      'jewelry stand',
      'jewelry organizer',
      'earring',
      'eardrop',
      'ear stud',
      'ear clip',
      'pearl',
      'vintage jewelry',
      'asymmetric',
      'temperament',
      'ethnic',
      'bohemian',
      'rhinestone',
      'zircon',
      'cubic zirconia',
      'sapphire',
      'ruby',
      'emerald',
      'diamond',
      'opal',
      'turquoise',
      'agate',
      'jade',
      'stainless steel jewelry',
      'titanium jewelry',
      'magnetic jewelry',
    ],
  },
  {
    slug: 'health-beauty',
    name: 'Health & Beauty',
    keywords: [
      'skincare',
      'makeup',
      'cosmetic',
      'brush set',
      'lipstick',
      'foundation',
      'mascara',
      'eyelash',
      'nail',
      'manicure',
      'pedicure',
      'hair dryer',
      'hair straightener',
      'curling iron',
      'shaver',
      'razor',
      'trimmer',
      'epilator',
      'derma',
      'facial',
      'serum',
      'cream',
      'lotion',
      'essential oil',
      'aromatherapy',
      'diffuser',
      'massage',
      'massager',
      'blood pressure',
      'thermometer',
      'scale',
      'teeth whitening',
      'wig',
      'hair extension',
      'hair removal',
      'depilatory',
      'sunscreen',
      'perfume',
      'cologne',
      'vitamin',
      'supplement',
      'first aid',
      'bandage',
      'brace',
      'support sleeve',
      'heating pad',
      'ice pack',
      'compress',
      'shampoo',
      'conditioner',
      'hair care',
      'hair mask',
      'hair oil',
      'soap bar',
      'body wash',
      'body care',
      'moisturizer',
      'cleanser',
      'toner',
      'mask face',
      'mask skin',
      'mask pore',
      'collagen',
      'anti-aging',
      'wrinkle',
      'dark circle',
      'acne',
      'blemish',
      'whitening',
      'brightening',
      'soothing',
      'repair cream',
      'repair paste',
      'patch body',
      'belly button patch',
      'eye patch beauty',
      'foot patch',
      'detox',
      'herbal',
      'tea health',
      'sugar soothing',
      'nourishing',
      'polygonum',
      'black tea mask',
      'pore',
      'deep cleansing',
      'exfoliat',
      'compact',
      'finishing powder',
      'foundation',
      'concealer',
      'blush makeup',
      'eyeshadow',
      'eyeliner',
      'eye cream',
      'body patch',
      'shaping',
      'slimming',
      'firming',
      'tummy',
      'cellulite',
      'creatine',
      'protein powder',
      'pre-workout',
      'BCAA',
      'collagen supplement',
      'probiotic',
      'omega',
      'melatonin',
      'CBD',
      'hemp',
      'pain relief',
      'muscle',
      'joint',
      'knee brace',
      'ankle brace',
      'wrist brace',
      'posture corrector',
      'compression',
      'orthopedic',
      'insole',
      'foot care',
      'corn remover',
      'bunion',
      'ingrown',
      'dental',
      'oral care',
      'mouthwash',
      'floss',
      'tongue scraper',
      'eye mask sleep',
      'ear plug',
      'essential oil diffuser',
      'incense',
      'sage',
      'smudge',
    ],
  },
  {
    slug: 'fashion',
    name: 'Fashion',
    keywords: [
      'shirt',
      'dress',
      'jacket',
      'coat',
      'hoodie',
      'sweater',
      'pants',
      'jeans',
      'shorts',
      'skirt',
      'blouse',
      'vest',
      'cardigan',
      'romper',
      'jumpsuit',
      'legging',
      'sock',
      'underwear',
      'bra',
      'lingerie',
      'swimsuit',
      'bikini',
      'trunks',
      'hat',
      'cap',
      'beanie',
      'scarf',
      'glove',
      'belt',
      'wallet',
      'purse',
      'handbag',
      'backpack',
      'luggage',
      'suitcase',
      'watch band',
      'sunglasses',
      'tie',
      'bow tie',
      'shoe',
      'boot',
      'sandal',
      'slipper',
      'sneaker',
      'heel',
      'costume',
      'cosplay',
      'apron',
      'uniform',
      'robe',
      'pajama',
      'kimono',
      'suspender',
      'one-shoulder',
      'commuter bag',
      'tote bag',
      'crossbody',
      'messenger bag',
      'clutch',
      'duffel',
      'garment bag',
      'travel bag',
      'fanny pack',
      'wristlet',
      'hair accessory',
      'headband',
      'hair clip',
      'scrunchie',
      'bandana',
      'poncho',
      'cape',
      'shawl',
      'wrap fashion',
      'corset',
      'bodysuit',
      'camisole',
      'tank top',
      'crop top',
      'tunic',
      'maxi',
      'midi',
      'mini skirt',
      'cargo',
      'chino',
      'overalls',
      'dungaree',
      'blazer',
      'trench',
      'parka',
      'windbreaker',
      'fleece',
      'down jacket',
      'denim',
      'leather jacket',
      'fur',
      'knit',
      'crochet',
      'embroidered',
      'sequin',
      'lace',
      'satin',
      'velvet',
      'chiffon',
      'georgette',
      'organza',
      'tulle',
      'literary',
      'large size',
      'plus size',
      'fat sister',
      'oversized',
      'one piece',
      'two piece set',
      'matching set',
      'co-ord',
      'lounge set',
      'tracksuit',
      'sweatsuit',
      'activewear fashion',
      'athleisure',
      'vintage fashion',
      'retro',
      'boho',
      'bohemian fashion',
      'preppy',
      'streetwear',
      'Y2K',
      'aesthetic',
      'cottagecore',
      'dark academia',
      'minimalist fashion',
      'jean',
      'denim skirt',
      'denim jacket',
      'leather belt',
      'canvas belt',
      'woven belt',
      'elastic belt',
    ],
  },
  {
    slug: 'sports-outdoors',
    name: 'Sports & Outdoors',
    keywords: [
      'fitness',
      'exercise',
      'yoga',
      'gym',
      'dumbbell',
      'barbell',
      'kettlebell',
      'treadmill',
      'elliptical',
      'rowing machine',
      'resistance band',
      'workout',
      'boxing',
      'martial art',
      'cycling',
      'bicycle',
      'bike rack',
      'helmet',
      'skateboard',
      'scooter',
      'surfing',
      'swimming',
      'goggles',
      'snorkel',
      'kayak',
      'paddle',
      'fishing',
      'hunting',
      'camping',
      'tent',
      'sleeping bag',
      'hammock',
      'hiking',
      'climbing',
      'backpacking',
      'cooler',
      'thermos',
      'water bottle sport',
      'golf',
      'basketball',
      'football',
      'soccer',
      'baseball',
      'tennis',
      'badminton',
      'ping pong',
      'archery',
      'trampoline',
      'punching bag',
      'baseball',
      'softball',
      'volleyball',
      'hockey',
      'lacrosse',
      'cricket',
      'rugby',
      'wrestling',
      'climbing rope',
      'carabiner',
      'compass',
      'binocular',
      'flashlight tactical',
      'headlamp',
      'lantern camping',
      'cooler portable',
      'canteen',
      'survival',
      'paracord',
      'winch',
      'tow strap',
      'ATV',
      'UTV',
      'baseball net',
      'batting cage',
      'pitching',
      'softball glove',
      'basketball hoop',
      'goal net',
      'soccer goal',
      'tennis racket',
      'badminton racket',
      'ping pong paddle',
      'golf club',
      'golf bag',
      'putting',
      'archery target',
      'bow arrow',
      'crossbow',
      'pellet',
      'airsoft',
      'paintball',
      'dart',
      'dartboard',
      'pool table',
      'foosball',
      'cornhole',
      'bocce',
      'croquet',
      'horseshoe',
      'disc golf',
      'frisbee',
      'kite',
      'metal detector',
      'telescope',
      'binocular',
      'spotting scope',
      'hay spear',
      'bale spear',
      'skid steer',
      'tractor attachment',
      'ATV accessory',
      'winch strap',
    ],
  },
  {
    slug: 'kitchen-dining',
    name: 'Kitchen & Dining',
    keywords: [
      'kitchen',
      'cooking',
      'cookware',
      'pot',
      'pan',
      'skillet',
      'wok',
      'baking',
      'spatula',
      'whisk',
      'ladle',
      'tongs',
      'cutting board',
      'knife set',
      'chef knife',
      'blender',
      'mixer',
      'juicer',
      'toaster',
      'coffee maker',
      'coffee grinder',
      'espresso',
      'kettle',
      'air fryer',
      'instant pot',
      'slow cooker',
      'rice cooker',
      'food processor',
      'can opener',
      'peeler',
      'grater',
      'colander',
      'strainer',
      'measuring cup',
      'rolling pin',
      'cookie cutter',
      'cake',
      'muffin',
      'pie',
      'oven mitt',
      'trivet',
      'spice rack',
      'dish rack',
      'dish towel',
      'plate',
      'bowl set',
      'mug',
      'glass set',
      'wine',
      'corkscrew',
      'bottle opener',
      'chopstick',
      'utensil set',
      'food storage',
      'lunch box',
      'thermos food',
      'ice cream maker',
      'waffle maker',
      'griddle',
      'barbecue',
      'BBQ',
      'grill',
      'smoker',
      'charcoal',
      'meat thermometer',
      'apron kitchen',
      'knife',
      'cleaver',
      'butcher',
      'steak knife',
      'scissors kitchen',
      'peeler',
      'chopper',
      'slicer',
      'mandoline',
      'refrigerator',
      'fridge',
      'microwave',
      'oven',
      'dishwasher',
      'ice maker',
      'water filter',
      'food scale',
      'timer kitchen',
      'egg',
      'bread',
      'pizza',
      'meat',
      'vegetable',
      'fruit',
      'tea set',
      'teapot',
      'cup set',
      'dinner set',
      'tablecloth',
      'placemat',
      'napkin',
      'serving tray',
      'cake stand',
      'cookie jar',
      'salt pepper',
      'condiment',
      'sushi',
      'bamboo steamer',
      'wonton',
      'noodle',
      'pasta maker',
    ],
  },
  {
    slug: 'garden-outdoor',
    name: 'Garden & Outdoor',
    keywords: [
      'garden',
      'plant',
      'planter',
      'pot ceramic outdoor',
      'flower pot',
      'seed',
      'soil',
      'fertilizer',
      'compost',
      'watering can',
      'sprinkler',
      'hose',
      'lawn',
      'mower',
      'trimmer hedge',
      'weed',
      'rake',
      'shovel',
      'wheelbarrow',
      'greenhouse',
      'raised bed',
      'trellis',
      'fence',
      'gate',
      'gazebo',
      'pergola',
      'canopy',
      'awning',
      'patio',
      'deck',
      'porch',
      'outdoor furniture',
      'umbrella patio',
      'solar light',
      'pathway',
      'bird feeder',
      'bird bath',
      'bird house',
      'fountain',
      'pond',
      'statue garden',
      'gnome',
      'wind chime',
      'flag',
      'banner outdoor',
      'fire pit',
      'chiminea',
      'pool',
      'hot tub',
      'inflatable pool',
      'carport',
      'shed outdoor',
      'mailbox',
      'house number',
      'doormat',
      'welcome sign',
      'outdoor rug',
      'patio heater',
      'mosquito',
      'citronella',
      'outdoor curtain',
      'gas cylinder',
      'propane',
      'LP tank',
      'fire pit table',
      'outdoor heater',
      'patio set',
      'garden table',
      'park bench',
      'adirondack',
      'rattan',
      'wicker',
      'resin outdoor',
      'metal outdoor',
      'wooden outdoor',
      'storage shed',
      'deck box',
      'garden hose reel',
      'sprayer',
      'nozzle',
      'irrigation',
      'drip system',
      'rain barrel',
      'compost bin',
      'worm bin',
      'potting bench',
      'garden kneeler',
      'garden glove',
      'pruner',
      'secateur',
      'lopper',
      'hedge trimmer outdoor',
      'leaf blower',
      'snow blower',
      'snow shovel',
      'ice melt',
      'de-icer',
      'grill cover',
      'smoker cover',
      'outdoor cover',
      'furniture cover',
      'tarp',
      'shade sail',
      'retractable awning',
      'outdoor fan',
      'bug zapper',
      'mosquito net',
      'citronella candle',
      'tiki torch',
    ],
  },
  {
    slug: 'storage-organization',
    name: 'Storage & Organization',
    keywords: [
      'organizer',
      'storage bin',
      'storage box',
      'shelf unit',
      'shelving',
      'rack mount',
      'closet',
      'wardrobe organizer',
      'shoe rack',
      'shoe cabinet',
      'hanger',
      'hook wall',
      'drawer organizer',
      'basket storage',
      'container',
      'label maker',
      'filing cabinet',
      'locker',
      'pegboard',
      'garage storage',
      'tool chest',
      'cart rolling',
      'bookshelf',
      'display case',
      'display shelf',
      'cube storage',
      'stackable',
      'foldable storage',
      'vacuum bag storage',
      'under bed storage',
      'over door',
      'cabinet organizer',
      'pantry organizer',
      'lazy susan',
      'turntable storage',
      'magazine rack',
      'mail organizer',
      'key holder',
      'coat rack',
      'umbrella stand',
      'wine rack',
      'spice organizer',
      'toy storage',
      'laundry basket',
      'hamper',
      'drying rack',
      'ironing board',
    ],
  },
  {
    slug: 'tools-hardware',
    name: 'Tools & Hardware',
    keywords: [
      'tool set',
      'wrench',
      'drill',
      'screwdriver',
      'saw',
      'plier',
      'hammer',
      'socket',
      'ratchet',
      'tape measure',
      'level',
      'stud finder',
      'multimeter',
      'soldering',
      'welding',
      'clamp',
      'vise',
      'sander',
      'grinder',
      'router power',
      'jigsaw',
      'circular saw',
      'chainsaw',
      'air compressor',
      'nail gun',
      'rivet',
      'bolt',
      'nut',
      'washer',
      'anchor',
      'hinge',
      'lock',
      'deadbolt',
      'door handle',
      'knob',
      'latch',
      'weatherstrip',
      'caulk',
      'adhesive',
      'epoxy',
      'paint',
      'primer',
      'brush roller',
      'sandpaper',
      'putty',
      'wire stripper',
      'crimper',
      'voltage tester',
      'extension cord',
      'power strip',
      'surge protector',
      'generator',
      'inverter',
      'pressure washer',
      'jack car',
      'tow',
      'ramp',
      'diagnostic',
      'OBD',
      'car cover',
      'floor mat car',
      'wiper',
      'bulb car',
      'fuse',
      'dent puller',
      'dent repair',
      'paintless',
      'body repair',
      'car repair',
      'car tool',
      'diagnostic tool',
      'OBD',
      'torque',
      'impact',
      'pneumatic',
      'hydraulic',
      'jack stand',
      'creeper',
      'funnel',
      'oil drain',
      'battery charger car',
      'jump starter',
      'tire',
      'wheel',
      'lug',
      'spark plug',
      'air filter car',
      'wiper blade',
      'headlight bulb',
      'fuse car',
      'relay',
      'switch electrical',
      'breaker',
      'outlet',
      'junction box',
      'conduit',
      'wire connector',
      'heat shrink',
      'zip tie',
      'cable tie',
      'tool cart',
      'tool chest',
      'tool box',
      'tool set',
      'multifunctional tool',
      'mechanic',
      'automotive repair',
      'headlight repair',
      'body filler',
      'spray paint',
      'rust',
      'lubricant',
      'WD',
      'grease',
      'penetrant',
      'sealant',
      'silicone',
      'cement',
      'mortar',
      'concrete',
      'masonry',
      'drywall',
      'plaster',
      'stucco',
      'insulation',
      'roofing',
      'gutter',
      'downspout',
      'flashing',
      'pipe',
      'plumbing',
      'PVC pipe',
      'copper pipe',
      'fitting',
      'valve',
      'faucet repair',
      'gasket',
      'O-ring',
      'washer plumbing',
      'water heater',
      'sump pump',
      'septic',
      'drain snake',
      'auger',
      'compactor',
      'excavator',
      'loader',
    ],
  },
  {
    slug: 'home-furniture',
    name: 'Home & Furniture',
    keywords: [
      'sofa',
      'couch',
      'sectional',
      'chair',
      'recliner',
      'futon',
      'ottoman',
      'bench',
      'table dining',
      'table coffee',
      'table side',
      'table console',
      'desk',
      'bed frame',
      'headboard',
      'nightstand',
      'dresser',
      'chest of drawers',
      'mirror',
      'cabinet',
      'buffet',
      'sideboard',
      'bookcase',
      'entertainment center',
      'TV stand',
      'fireplace',
      'fan ceiling',
      'fan standing',
      'humidifier',
      'dehumidifier',
      'air purifier',
      'heater',
      'thermostat',
      'curtain',
      'drape',
      'blind',
      'shade window',
      'rug',
      'carpet',
      'mat floor',
      'throw pillow',
      'cushion',
      'blanket',
      'duvet',
      'comforter',
      'bedding set',
      'sheet set',
      'pillowcase',
      'towel',
      'bath mat',
      'shower curtain',
      'clock',
      'vase',
      'candle',
      'picture frame',
      'wall art',
      'tapestry',
      'figurine',
      'sculpture',
      'wreath',
      'seasonal decor',
      'christmas',
      'halloween',
      'lamp',
      'chandelier',
      'sconce',
      'floor lamp',
      'table lamp',
      'ceiling light',
      'night light',
      'string light',
      'LED strip',
      'vanity',
      'bathroom cabinet',
      'faucet',
      'shower head',
      'toilet',
      'sink',
      'soap dispenser',
      'trash can',
      'step stool',
      'clothes steamer',
      'iron clothes',
      'sewing machine',
      'vacuum',
      'mop',
      'broom',
      'steam cleaner',
      'message board',
      'sticker wall',
      'glass sticker',
      'decal',
      'decor wall',
      'coffee table',
      'dining table',
      'side table',
      'console table',
      'end table',
      'accent table',
      'nesting table',
      'bar stool',
      'counter stool',
      'rocking chair',
      'accent chair',
      'gaming chair',
      'office chair',
      'loveseat',
      'daybed',
      'murphy bed',
      'bunk bed',
      'loft bed',
      'trundle',
      'canopy bed',
      'platform bed',
      'adjustable bed',
      'standing desk',
      'L-shaped desk',
      'corner desk',
      'computer desk',
    ],
  },
];

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function matchesKeyword(name, keyword) {
  const pattern = new RegExp(`\\b${escapeRegex(keyword).replace(/\\s+/g, '\\\\s+')}\\b`, 'i');
  return pattern.test(name);
}

async function ensureCategories() {
  const existing = await supabaseGet('mi_categories', 'select=id,slug,name,product_count');
  const desiredBySlug = new Map(TARGET_CATEGORIES.map((cat) => [cat.slug, cat]));
  const desiredByName = new Map(TARGET_CATEGORIES.map((cat) => [cat.name.toLowerCase(), cat]));

  const toRename = [];
  for (const cat of existing) {
    if (cat.name.toLowerCase() === 'home & garden') {
      toRename.push({ id: cat.id, name: 'Home & Furniture', slug: 'home-furniture' });
    }
    if (cat.name.toLowerCase() === 'kitchen') {
      toRename.push({ id: cat.id, name: 'Kitchen & Dining', slug: 'kitchen-dining' });
    }
  }

  for (const rename of toRename) {
    if (APPLY) {
      await supabasePatch('mi_categories', `id=eq.${rename.id}`, {
        name: rename.name,
        slug: rename.slug,
      });
    }
  }

  const updated = await supabaseGet('mi_categories', 'select=id,slug,name,product_count');
  const existingBySlug = new Map(updated.map((cat) => [cat.slug, cat]));

  const toCreate = [];
  for (const desired of TARGET_CATEGORIES) {
    if (!existingBySlug.has(desired.slug)) {
      toCreate.push(desired);
    }
  }
  if (toCreate.length > 0 && APPLY) {
    await supabaseInsert('mi_categories', toCreate.map((cat) => ({ name: cat.name, slug: cat.slug })));
  }

  const afterCreate = await supabaseGet('mi_categories', 'select=id,slug,name,product_count');
  const finalBySlug = new Map(afterCreate.map((cat) => [cat.slug, cat]));

  const toDelete = afterCreate.filter(
    (cat) =>
      !desiredBySlug.has(cat.slug) &&
      !desiredByName.has(cat.name.toLowerCase())
  );

  return { categories: afterCreate, mapBySlug: finalBySlug, toDelete };
}

async function fetchAllActiveProducts() {
  const results = [];
  const pageSize = 1000;
  let offset = 0;
  while (true) {
    const batch = await supabaseGet(
      'mi_products',
      `select=id,name,category_id,mi_categories(name,slug)&status=eq.active&order=id.asc&limit=${pageSize}&offset=${offset}`
    );
    if (!batch.length) break;
    results.push(...batch);
    offset += pageSize;
  }
  return results;
}

async function main() {
  console.log('=== Recategorize All Products ===\n');
  console.log(`Mode: ${APPLY ? 'APPLY' : 'DRY RUN'}\n`);

  const { mapBySlug, toDelete } = await ensureCategories();
  const products = await fetchAllActiveProducts();

  const beforeCounts = {};
  const afterCounts = {};
  let recategorized = 0;
  const unmatched = [];
  const updatesByCategory = new Map();

  for (const product of products) {
    const currentSlug = product.mi_categories?.slug || '';
    beforeCounts[currentSlug] = (beforeCounts[currentSlug] || 0) + 1;

    let matchedSlug = null;
    for (const category of CATEGORY_KEYWORDS) {
      if (category.keywords.some((kw) => matchesKeyword(product.name || '', kw))) {
        matchedSlug = category.slug;
        break;
      }
    }

    if (!matchedSlug) {
      unmatched.push(product.name || '(unnamed)');
      if (currentSlug === 'home-garden') {
        matchedSlug = 'home-furniture';
      } else if (currentSlug === 'kitchen') {
        matchedSlug = 'kitchen-dining';
      } else {
        matchedSlug = currentSlug || null;
      }
    }

    const keepIfMatchesCurrent =
      currentSlug &&
      currentSlug !== 'home-garden' &&
      currentSlug !== 'home-furniture' &&
      CATEGORY_KEYWORDS.some(
        (cat) => cat.slug === currentSlug && cat.keywords.some((kw) => matchesKeyword(product.name || '', kw))
      );

    if (keepIfMatchesCurrent) {
      matchedSlug = currentSlug;
    }

    if (matchedSlug && matchedSlug !== currentSlug) {
      recategorized += 1;
      const targetCategory = mapBySlug.get(matchedSlug);
      if (targetCategory) {
        const list = updatesByCategory.get(targetCategory.id) || [];
        list.push(product.id);
        updatesByCategory.set(targetCategory.id, list);
      }
    }

    const finalSlug = matchedSlug || currentSlug || 'unmatched';
    afterCounts[finalSlug] = (afterCounts[finalSlug] || 0) + 1;
  }

  if (APPLY) {
    for (const [categoryId, productIds] of updatesByCategory.entries()) {
      for (let i = 0; i < productIds.length; i += 50) {
        const batch = productIds.slice(i, i + 50);
        await supabasePatch('mi_products', `id=in.(${batch.join(',')})`, {
          category_id: categoryId,
        });
      }
    }

    for (const [slug, count] of Object.entries(afterCounts)) {
      const cat = mapBySlug.get(slug);
      if (cat) {
        await supabasePatch('mi_categories', `id=eq.${cat.id}`, { product_count: count });
      }
    }

    if (toDelete.length > 0) {
      const ids = toDelete.map((c) => c.id);
      await supabaseDelete('mi_categories', `id=in.(${ids.join(',')})`);
    }
  }

  console.log('=== Summary ===');
  console.log('Before counts:');
  Object.entries(beforeCounts)
    .sort((a, b) => b[1] - a[1])
    .forEach(([slug, count]) => console.log(`  ${slug || 'none'}: ${count}`));
  console.log('\nAfter counts:');
  Object.entries(afterCounts)
    .sort((a, b) => b[1] - a[1])
    .forEach(([slug, count]) => console.log(`  ${slug || 'none'}: ${count}`));

  console.log(`\nRecategorized: ${recategorized}`);
  console.log(`Unmatched: ${unmatched.length}`);
  if (unmatched.length > 0) {
    console.log('\nUnmatched samples:');
    unmatched.slice(0, 20).forEach((name) => console.log(`  - ${name}`));
  }
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
